version: "3.8"

services:
  db:
    image: postgres:12.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meu_banco
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
